name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development  # Referencia o ambiente de desenvolvimento criado

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=16.7.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Set up environment variables
        run: |
          echo "ENV=development" >> $GITHUB_ENV
          echo "API_URL=http://localhost:3000" >> $GITHUB_ENV

      - name: Deploy to Development Environment
        run: |
          echo "Deploying to Development Environment"
