# .github/workflows/another-dev-workflow.yml
name: Another Dev Workflow

on:
  workflow_dispatch:
    inputs:
      dev-env-name:
        description: 'Another Dev Environment Name'
        required: true
      ttl:
        description: Select TTL environment (hours)
        required: true
        type: choice
        default: 'dev1h'
        options:
          - 'dev1h'
          - 'dev3h'
          - 'dev6h'

env:
  APP_NAME: another-fsd
  PROJECT_NAME: another-main-dasdad
  SH8: ${{ github.sha }}
  STACK_NAME: "${{ github.event.inputs.ttl }}-${{ github.event.inputs.dev-env-name }}"
  PUBLIC_URL: "https://b${{ github.event.inputs.ttl }}-${{ github.event.inputs.dev-env-name }}.another-dev.com/"
  GITHUB_WORKFLOW: "📦🚀 Create Another Dev Environment ${{ github.event.inputs.dev-env-name }}"
  DEV_STACK_TTL: "1d"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: another-development  # Referência a um ambiente de desenvolvimento separado

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=16.7.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Set up environment variables
        run: |
          echo "ENV=another-development" >> $GITHUB_ENV
          echo "API_URL=http://localhost:3001" >> $GITHUB_ENV

      - name: Deploy to Another Development Environment
        run: |
          echo "Deploying to Another Development Environment"
          echo "Using STACK_NAME: ${{ env.STACK_NAME }}"
          echo "Public URL: ${{ env.PUBLIC_URL }}"
          # Adicione seu script de deploy aqui
